///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace Vip
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Vip_AUT recording.
    /// </summary>
    [TestModule("497e0d0d-ed47-4f97-9dfe-1aa90fb0cf8c", ModuleType.Recording, 1)]
    public partial class Vip_AUT : ITestModule
    {
        /// <summary>
        /// Holds an instance of the VipRepository repository.
        /// </summary>
        public static VipRepository repo = VipRepository.Instance;

        static Vip_AUT instance = new Vip_AUT();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Vip_AUT()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Vip_AUT Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Run application 'D:\\jagadeesh\\Data\\Rx\\Files\\VipV1.exe' with arguments '' in normal mode.", new RecordItemIndex(0));
            Host.Local.RunApplication("D:\\jagadeesh\\Data\\Rx\\Files\\VipV1.exe", "", "D:\\jagadeesh\\Data\\Rx\\Files", false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormVipApplication.FirstName' at 35;8.", repo.FormVipApplication.FirstNameInfo, new RecordItemIndex(1));
            repo.FormVipApplication.FirstName.Click("35;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LShiftKey down}J{LShiftKey up}ohn' with focus on 'FormVipApplication.FirstName'.", repo.FormVipApplication.FirstNameInfo, new RecordItemIndex(2));
            repo.FormVipApplication.FirstName.PressKeys("{LShiftKey down}J{LShiftKey up}ohn");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormVipApplication.LastName' at 36;9.", repo.FormVipApplication.LastNameInfo, new RecordItemIndex(3));
            repo.FormVipApplication.LastName.Click("36;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LShiftKey down}D{LShiftKey up}oe' with focus on 'FormVipApplication.LastName'.", repo.FormVipApplication.LastNameInfo, new RecordItemIndex(4));
            repo.FormVipApplication.LastName.PressKeys("{LShiftKey down}D{LShiftKey up}oe");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormVipApplication.Music' at 26;7.", repo.FormVipApplication.MusicInfo, new RecordItemIndex(5));
            repo.FormVipApplication.Music.Click("26;7");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormVipApplication.Male' at 17;10.", repo.FormVipApplication.MaleInfo, new RecordItemIndex(6));
            repo.FormVipApplication.Male.Click("17;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormVipApplication.ButtonAdd' at 31;10.", repo.FormVipApplication.ButtonAddInfo, new RecordItemIndex(7));
            repo.FormVipApplication.ButtonAdd.Click("31;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormVipApplication.Delete' at 53;11.", repo.FormVipApplication.DeleteInfo, new RecordItemIndex(8));
            repo.FormVipApplication.Delete.Click("53;11");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FormVipApplication.Close' at 20;9.", repo.FormVipApplication.CloseInfo, new RecordItemIndex(9));
            repo.FormVipApplication.Close.Click("20;9");
            Delay.Milliseconds(200);
            
            //report_cutom();
            //Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
