///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Vip
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the VipRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
    [RepositoryFolder("bacfb6ea-536a-4552-a361-80c9c0263bd7")]
    public partial class VipRepository : RepoGenBaseFolder
    {
        static VipRepository instance = new VipRepository();
        VipRepositoryFolders.FormVipApplicationAppFolder _formvipapplication;

        /// <summary>
        /// Gets the singleton class instance representing the VipRepository element repository.
        /// </summary>
        [RepositoryFolder("bacfb6ea-536a-4552-a361-80c9c0263bd7")]
        public static VipRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public VipRepository() 
            : base("VipRepository", "/", null, 0, false, "bacfb6ea-536a-4552-a361-80c9c0263bd7", ".\\RepositoryImages\\VipRepositorybacfb6ea.rximgres")
        {
            _formvipapplication = new VipRepositoryFolders.FormVipApplicationAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("bacfb6ea-536a-4552-a361-80c9c0263bd7")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The FormVipApplication folder.
        /// </summary>
        [RepositoryFolder("c81cc15e-17bc-4b51-873a-c6900ff7690f")]
        public virtual VipRepositoryFolders.FormVipApplicationAppFolder FormVipApplication
        {
            get { return _formvipapplication; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
    public partial class VipRepositoryFolders
    {
        /// <summary>
        /// The FormVipApplicationAppFolder folder.
        /// </summary>
        [RepositoryFolder("c81cc15e-17bc-4b51-873a-c6900ff7690f")]
        public partial class FormVipApplicationAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _firstnameInfo;
            RepoItemInfo _lastnameInfo;
            RepoItemInfo _musicInfo;
            RepoItemInfo _maleInfo;
            RepoItemInfo _buttonaddInfo;
            RepoItemInfo _deleteInfo;
            RepoItemInfo _closeInfo;

            /// <summary>
            /// Creates a new FormVipApplication  folder.
            /// </summary>
            public FormVipApplicationAppFolder(RepoGenBaseFolder parentFolder) :
                    base("FormVipApplication", "/form[@controlname='formVipApplication']", parentFolder, 30000, null, true, "c81cc15e-17bc-4b51-873a-c6900ff7690f", "")
            {
                _firstnameInfo = new RepoItemInfo(this, "FirstName", "text[@controlname='tbFirstName']", 30000, null, "e92231fa-35ea-4bc1-93d9-63ba4d4bedee");
                _lastnameInfo = new RepoItemInfo(this, "LastName", "?/?/text[@accessiblename='Last Name:' and @accessiblerole='Text']", 30000, null, "4a114c27-bdf2-4031-8ce3-6ef43c662454");
                _musicInfo = new RepoItemInfo(this, "Music", "list[@controlname='lbCategory']/?/?/listitem[@accessiblename='Music']", 30000, null, "62f15d3b-7b53-4a19-ae0e-22dc2978512a");
                _maleInfo = new RepoItemInfo(this, "Male", "container[@controlname='groupBox2']/radiobutton[@controlname='rbMale']", 30000, null, "72f18766-5a15-49d6-b28e-5ad7afaba32f");
                _buttonaddInfo = new RepoItemInfo(this, "ButtonAdd", "button[@controlname='btAdd']", 30000, null, "2befd967-3205-49c9-9a43-7ff8b55cf611");
                _deleteInfo = new RepoItemInfo(this, "Delete", "button[@controlname='btDelete']", 30000, null, "9335dfd2-c0d8-4e2e-8a18-823a64d27851");
                _closeInfo = new RepoItemInfo(this, "Close", "titlebar/button[@accessiblename='Close']", 30000, null, "65b0f878-334c-4c89-97d3-117f10dc69e5");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c81cc15e-17bc-4b51-873a-c6900ff7690f")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c81cc15e-17bc-4b51-873a-c6900ff7690f")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FirstName item.
            /// </summary>
            [RepositoryItem("e92231fa-35ea-4bc1-93d9-63ba4d4bedee")]
            public virtual Ranorex.Text FirstName
            {
                get
                {
                    return _firstnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The FirstName item info.
            /// </summary>
            [RepositoryItemInfo("e92231fa-35ea-4bc1-93d9-63ba4d4bedee")]
            public virtual RepoItemInfo FirstNameInfo
            {
                get
                {
                    return _firstnameInfo;
                }
            }

            /// <summary>
            /// The LastName item.
            /// </summary>
            [RepositoryItem("4a114c27-bdf2-4031-8ce3-6ef43c662454")]
            public virtual Ranorex.Text LastName
            {
                get
                {
                    return _lastnameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LastName item info.
            /// </summary>
            [RepositoryItemInfo("4a114c27-bdf2-4031-8ce3-6ef43c662454")]
            public virtual RepoItemInfo LastNameInfo
            {
                get
                {
                    return _lastnameInfo;
                }
            }

            /// <summary>
            /// The Music item.
            /// </summary>
            [RepositoryItem("62f15d3b-7b53-4a19-ae0e-22dc2978512a")]
            public virtual Ranorex.ListItem Music
            {
                get
                {
                    return _musicInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The Music item info.
            /// </summary>
            [RepositoryItemInfo("62f15d3b-7b53-4a19-ae0e-22dc2978512a")]
            public virtual RepoItemInfo MusicInfo
            {
                get
                {
                    return _musicInfo;
                }
            }

            /// <summary>
            /// The Male item.
            /// </summary>
            [RepositoryItem("72f18766-5a15-49d6-b28e-5ad7afaba32f")]
            public virtual Ranorex.RadioButton Male
            {
                get
                {
                    return _maleInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The Male item info.
            /// </summary>
            [RepositoryItemInfo("72f18766-5a15-49d6-b28e-5ad7afaba32f")]
            public virtual RepoItemInfo MaleInfo
            {
                get
                {
                    return _maleInfo;
                }
            }

            /// <summary>
            /// The ButtonAdd item.
            /// </summary>
            [RepositoryItem("2befd967-3205-49c9-9a43-7ff8b55cf611")]
            public virtual Ranorex.Button ButtonAdd
            {
                get
                {
                    return _buttonaddInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonAdd item info.
            /// </summary>
            [RepositoryItemInfo("2befd967-3205-49c9-9a43-7ff8b55cf611")]
            public virtual RepoItemInfo ButtonAddInfo
            {
                get
                {
                    return _buttonaddInfo;
                }
            }

            /// <summary>
            /// The Delete item.
            /// </summary>
            [RepositoryItem("9335dfd2-c0d8-4e2e-8a18-823a64d27851")]
            public virtual Ranorex.Button Delete
            {
                get
                {
                    return _deleteInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Delete item info.
            /// </summary>
            [RepositoryItemInfo("9335dfd2-c0d8-4e2e-8a18-823a64d27851")]
            public virtual RepoItemInfo DeleteInfo
            {
                get
                {
                    return _deleteInfo;
                }
            }

            /// <summary>
            /// The Close item.
            /// </summary>
            [RepositoryItem("65b0f878-334c-4c89-97d3-117f10dc69e5")]
            public virtual Ranorex.Button Close
            {
                get
                {
                    return _closeInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Close item info.
            /// </summary>
            [RepositoryItemInfo("65b0f878-334c-4c89-97d3-117f10dc69e5")]
            public virtual RepoItemInfo CloseInfo
            {
                get
                {
                    return _closeInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}